### ISSUE TITLE
Ingfokan

### ISSUE THREAD

**Issue by AnggaSP** [angeloanan/notifi-printer#1]
ingfo

**Comment by angeloanan** [comment]
ingfokan rosak 👎 
![image](https://github.com/user-attachments/assets/a619a2e8-6db2-4863-9061-c0c03304e9c7)

**Comment by angeloanan** [comment]
Di ingfokan mungkin sudah benar tetapi harus testing

**Comment by angsanley** [comment]
🔥💀😫💨😱😱🤬💨🤬🥰🏢ℹ️🎉

**Comment by angeloanan** [comment]
oghe sudah benar, tak tutup

**Comment by angsanley** [comment]
mijau
